### ISSUE TITLE
How to use markdown instead of asciidoc?

### ISSUE THREAD

**Issue by smaret** [sluedecke/atom-diary#3]
When adding a new entry, the package creates a asciidoc file. How can I make a markdown file instead?

**Comment by sluedecke** [comment]
AsciiDoc is the default setting, so you need to configure it.  You should find the setting here:

Edit -> Preferences -> Packages -> (search for or scroll down to atom-diary) -> Settings -> "Markup Language to be used for diary files"

Looks complicated, but appears to be the standard way for Atom.

**Comment by smaret** [comment]
Thanks!
